version: '3'
services:
  polygon-graph-node:
    image: graphprotocol/graph-node
    ports:
      - '10000:8000'
      - '10001:8001'
      - '10020:8020'
      - '10030:8030'
      - '10040:8040'
    environment:
      postgres_host: 172.17.0.1
      postgres_user: postgres
      postgres_pass: moneymoneyHOME888
      postgres_db: polygon-graphnode
      ipfs: '172.17.0.1:5001'
      ethereum: 'mainnet:https://polygon-rpc.com/'
      GRAPH_LOG: warn
      GRAPH_ALLOW_NON_DETERMINISTIC_IPFS: 'true'
